# Generated by Django 5.0.3 on 2024-03-31 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('mobile1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Mobile')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('contact_person_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Person Mobile')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Disabled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Customer Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Pincode')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='customer_pics/', verbose_name='Profile Picture')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customer_logos/', verbose_name='Logo')),
                ('mobile1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Mobile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('conatct_person_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Person Mobile')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Disabled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Users Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Employee'), (4, 'Student')], default=3)),
                ('dob', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Disabled')], default=1)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('N', 'No Prefrence'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N', max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='account.customerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('customer', 'branch_name')},
        ),
    ]
