# Generated by Django 5.0.3 on 2024-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo1',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/', verbose_name='Logo'),
        ),
    ]
