# Generated by Django 5.0.3 on 2024-05-08 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_startdate', models.DateField()),
                ('session_enddate', models.DateField()),
                ('session_displayformat', models.CharField(max_length=100)),
                ('session_description', models.CharField(max_length=255, null=True)),
                ('session_status', models.IntegerField(choices=[(1, 'Active'), (2, 'In-Active')], default=1)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discounthead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_name', models.CharField(max_length=100, unique=True)),
                ('discount_description', models.CharField(max_length=255, null=True)),
                ('discount_status', models.IntegerField(choices=[(1, 'Active'), (2, 'In-Active')], default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='discountheads', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeClassMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feehead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feehead_name', models.CharField(max_length=100, unique=True)),
                ('feehead_description', models.CharField(max_length=255)),
                ('feehead_status', models.IntegerField(choices=[(1, 'Active'), (2, 'In-Active')], default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feeheads', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeMonthMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finehead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fine_name', models.CharField(max_length=100, unique=True)),
                ('fine_description', models.TextField(null=True)),
                ('fine_status', models.IntegerField(choices=[(1, 'Active'), (2, 'In-Active')], default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fineheads', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_name', models.CharField(max_length=100, unique=True)),
                ('grade_comments', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grades', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_name', models.CharField(max_length=100, unique=True)),
                ('section_comments', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sections', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('frequency', models.IntegerField(choices=[(5, 'Daily'), (1, 'Monthly'), (2, 'Quaterly'), (3, 'Half-Yearly'), (4, 'Yearly')], default=1, null=True)),
                ('fine_max_calculated', models.IntegerField(default=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fine_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fines', to='adminmodule.academicyear')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('finehead', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fines', to='adminmodule.finehead')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grades', to='adminmodule.grade')),
            ],
            options={
                'unique_together': {('finehead', 'grade', 'fine_session')},
            },
        ),
        migrations.CreateModel(
            name='MonthMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthName', models.CharField(max_length=50)),
                ('monthCode', models.CharField(max_length=10)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('academicYear', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='monthmap_session', to='adminmodule.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='monthmap_branch', to='account.branch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('academicYear', 'branch', 'monthName')},
            },
        ),
    ]
