# Generated by Django 5.0.3 on 2024-05-09 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('adminmodule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeclassmap',
            name='academicYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_class_map_session', to='adminmodule.academicyear'),
        ),
        migrations.AddField(
            model_name='feeclassmap',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_class_map_branch', to='account.branch'),
        ),
        migrations.AddField(
            model_name='feeclassmap',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_class_map_grades', to='adminmodule.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='feeclassmap',
            unique_together={('grade', 'academicYear', 'branch')},
        ),
        migrations.CreateModel(
            name='FeeClassAmountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('feeClassMap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fee_class_amount_map_fee_class', to='adminmodule.feeclassmap')),
                ('feehead', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fee_class_map_heads', to='adminmodule.feehead')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
