# Generated by Django 5.0.3 on 2024-05-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0002_feeclassmap_academicyear_feeclassmap_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeclassamountmap',
            name='feeClassMap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_class_amount_map_fee_class', to='adminmodule.feeclassmap'),
        ),
    ]
