# Generated by Django 5.0.3 on 2024-06-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('adminmodule', '0003_alter_feeclassamountmap_feeclassmap'),
        ('universal', '0002_alter_cast_unique_together_remove_cast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemonthmap',
            name='academicYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_month_map_session', to='adminmodule.academicyear'),
        ),
        migrations.AddField(
            model_name='feemonthmap',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_month_map_branch', to='account.branch'),
        ),
        migrations.AddField(
            model_name='feemonthmap',
            name='feeHead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_month_map_feehead', to='adminmodule.feehead'),
        ),
        migrations.AddField(
            model_name='feemonthmap',
            name='monthMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_month_map_month', to='universal.month_master'),
        ),
        migrations.AlterUniqueTogether(
            name='feemonthmap',
            unique_together={('academicYear', 'branch', 'feeHead', 'monthMaster')},
        ),
    ]
