# Generated by Django 5.0.3 on 2024-06-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cast',
            name='category',
        ),
    ]
