# Generated by Django 5.0.3 on 2024-05-08 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('adminmodule', '0001_initial'),
        ('universal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Other', 'Other'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('student_pic', models.ImageField(blank=True, null=True, upload_to='student_pic/')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'In-Active')], default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('None', 'None')], default='None', max_length=50)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('bodytype', models.CharField(choices=[('Normal', 'Normal'), ('Blind', 'Blind'), ('Physically Challenged', 'Physically Challenged'), ('Other', 'Other')], default='Normal', max_length=50)),
                ('address_permanent', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_class', models.CharField(blank=True, max_length=255, null=True)),
                ('passing_year', models.IntegerField(blank=True, default=0, null=True)),
                ('tc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student_type', models.CharField(choices=[('Old', 'Old'), ('New', 'New')], default='Old', max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(choices=[('No Preference', 'No Preference'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Cousin', 'Cousin'), ('Father-in-law', 'Father-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Stepfather', 'Stepfather'), ('Stepmother', 'Stepmother'), ('Stepson', 'Stepson'), ('Stepdaughter', 'Stepdaughter'), ('Stepbrother', 'Stepbrother'), ('Stepsister', 'Stepsister'), ('Foster father', 'Foster father'), ('Foster mother', 'Foster mother'), ('Foster son', 'Foster son'), ('Foster daughter', 'Foster daughter'), ('Guardian', 'Guardian'), ('Legal guardian', 'Legal guardian'), ('Adoptive father', 'Adoptive father'), ('Adoptive mother', 'Adoptive mother'), ('Adopted son', 'Adopted son'), ('Adopted daughter', 'Adopted daughter'), ('Foster brother', 'Foster brother'), ('Foster sister', 'Foster sister'), ('Foster uncle', 'Foster uncle'), ('Foster aunt', 'Foster aunt'), ('Foster nephew', 'Foster nephew'), ('Foster niece', 'Foster niece'), ('Godfather', 'Godfather'), ('Godmother', 'Godmother'), ('Godson', 'Godson'), ('Goddaughter', 'Goddaughter'), ('Foster parent', 'Foster parent'), ('Foster child', 'Foster child')], default='No Preference', max_length=100)),
                ('guardian_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('status_school', models.CharField(choices=[('Own', 'Own'), ('Grant', 'Grant'), ('Other', 'Other')], default='Own', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='casts', to='universal.cast')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='universal.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='universal.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='provinces', to='universal.province')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAndAadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_front', models.ImageField(blank=True, null=True, upload_to='student_aadhar_front/')),
                ('aadhar_back', models.ImageField(blank=True, null=True, upload_to='student_aadhar_back/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banks', to='universal.bank')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bankstudents', to='student.registerstudent')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_date', models.DateField(auto_now_add=True)),
                ('classsrno', models.CharField(blank=True, max_length=255, null=True)),
                ('boardsrno', models.CharField(blank=True, max_length=255, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'In-Active')], default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academic_years', to='adminmodule.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='account.branch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academicstudentgrades', to='adminmodule.grade')),
                ('medium', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='academicstudentmediums', to='universal.medium')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academicstudentsections', to='adminmodule.section')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academicstudents', to='student.registerstudent')),
            ],
        ),
    ]
