# Generated by Django 5.0.3 on 2024-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='relationship',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Cousin', 'Cousin'), ('Father-in-law', 'Father-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Stepfather', 'Stepfather'), ('Stepmother', 'Stepmother'), ('Stepson', 'Stepson'), ('Stepdaughter', 'Stepdaughter'), ('Stepbrother', 'Stepbrother'), ('Stepsister', 'Stepsister'), ('Foster father', 'Foster father'), ('Foster mother', 'Foster mother'), ('Foster son', 'Foster son'), ('Foster daughter', 'Foster daughter'), ('Guardian', 'Guardian'), ('Legal guardian', 'Legal guardian'), ('Adoptive father', 'Adoptive father'), ('Adoptive mother', 'Adoptive mother'), ('Adopted son', 'Adopted son'), ('Adopted daughter', 'Adopted daughter'), ('Foster brother', 'Foster brother'), ('Foster sister', 'Foster sister'), ('Foster uncle', 'Foster uncle'), ('Foster aunt', 'Foster aunt'), ('Foster nephew', 'Foster nephew'), ('Foster niece', 'Foster niece'), ('Godfather', 'Godfather'), ('Godmother', 'Godmother'), ('Godson', 'Godson'), ('Goddaughter', 'Goddaughter'), ('Foster parent', 'Foster parent'), ('Foster child', 'Foster child')], default='No Preference', max_length=100),
        ),
    ]
